//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.External.SharpDevelop.ScriptSamples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class O2SampleScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal O2SampleScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Platform.External.SharpDevelop.Resources.ScriptSamples.O2SampleScripts", typeof(O2SampleScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using O2.Interfaces.O2Core;
        ///
        ///namespace O2.Views.ASCX.SourceCodeEdit.ScriptSamples
        ///{
        ///    public class HelloWorlds
        ///    {
        ///        public static IO2Log log = O2.Kernel.PublicDI.log;
        ///
        ///      
        ///        public static string sayHelloO2World()
        ///        {
        ///            string message = string.Format(&quot;Hello O2 World&quot;);
        ///            log.info [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1_helloWorld {
            get {
                return ResourceManager.GetString("_1_helloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Threading;
        ///
        ///namespace O2.Views.ASCX.SourceCodeEdit.ScriptSamples
        ///{
        ///    public class For_UnitTest_HotMethodPatch
        ///    {
        ///        public static int counterB;
        ///
        ///        public static void Main()
        ///        {
        ///            Console.WriteLine(&quot;This is a Embeded in O2 C# file that contains a nice multi-thread lo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _2_For_UnitTest_HotMethodPatch {
            get {
                return ResourceManager.GetString("_2_For_UnitTest_HotMethodPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Threading;
        ///
        ///namespace O2.Views.ASCX.SourceCodeEdit.ScriptSamples
        ///{
        ///    public class For_UnitTest_SimpleCalls
        ///    {
        ///        public static int count;
        ///        public static int sleepValue = 500;
        ///        public static string textToShow = &quot;&quot;;
        ///
        ///        public static void Main()
        ///        {
        ///            Con [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _4_For_UnitTest_SimpleCalls {
            get {
                return ResourceManager.GetString("_4_For_UnitTest_SimpleCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print &quot;**************************************************************&quot;
        ///print &quot;This is an Iron Phyton O2 Script&quot;
        ///print &quot;that will manually create a finding (with a trace) and saved it&quot;
        ///print &quot;**************************************************************&quot;
        ///
        ///import clr
        ///import sys
        ///
        ///sys.path.append(r&quot;E:\O2\_Bin_(O2_Binaries)&quot;)
        ///clr.AddReference(&quot;O2_Kernel&quot;)
        ///clr.AddReference(&quot;O2_DotNetWrappers&quot;)
        ///clr.AddReference(&quot;O2_ImportExport_OunceLabs&quot;)
        ///
        ///from O2.Kernel import *
        ///from O2.DotNetWrappers.O2Findings import *
        ///from O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IronPython_CreateFindingManually_py {
            get {
                return ResourceManager.GetString("IronPython_CreateFindingManually_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print &quot;This is an Iron Phyton O2 Script&quot;
        ///print &quot; &quot;
        ///print &quot;From here you have access to all the power of IronPython:&quot;
        ///print &quot; &quot;
        ///print 2+2.
        /// </summary>
        public static string IronPython_HelloWorld_py {
            get {
                return ResourceManager.GetString("IronPython_HelloWorld_py", resourceCulture);
            }
        }
    }
}
