//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.Views.ASCX.classes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class O2CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal O2CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Views.ASCX.classes.O2CoreResources", typeof(O2CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://deploy.o2-ounceopen.com/DemoFiles/Saved_Assessments_Files/WebGoat.zip.
        /// </summary>
        public static string DemoOzasmtFile_Hacmebank_WebGoat {
            get {
                return ResourceManager.GetString("DemoOzasmtFile_Hacmebank_WebGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://deploy.o2-ounceopen.com/DemoFiles/Saved_Assessments_Files/HacmeBank_WebServices.zip.
        /// </summary>
        public static string DemoOzasmtFile_Hacmebank_WebServices {
            get {
                return ResourceManager.GetString("DemoOzasmtFile_Hacmebank_WebServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://deploy.o2-ounceopen.com/DemoFiles/Saved_Assessments_Files/HacmeBank_Website.zip.
        /// </summary>
        public static string DemoOzasmtFile_Hacmebank_WebSite {
            get {
                return ResourceManager.GetString("DemoOzasmtFile_Hacmebank_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://deploy.o2-ounceopen.com/DemoFiles/ScanTargets/HacmeBank_WebServices_App_Code.dll.
        /// </summary>
        public static string DemoScanTarget_Dll_Hacmebank_WebService {
            get {
                return ResourceManager.GetString("DemoScanTarget_Dll_Hacmebank_WebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://deploy.o2-ounceopen.com/DemoFiles/ScanTargets/HacmeBank_WebSite_App_Code.dll.
        /// </summary>
        public static string DemoScanTarget_Dll_Hacmebank_WebSite {
            get {
                return ResourceManager.GetString("DemoScanTarget_Dll_Hacmebank_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;o2FindingsScriptLibrary&gt;
        ///  &lt;script title=&quot;Default o2Findings Linq Script&quot;&gt;from O2Finding finding in o2Findings select new {finding.vulnType , finding.vulnName, finding.confidence, finding.severity, finding.o2Traces, finding }&lt;/script&gt;
        ///  &lt;script title=&quot;Just VulnType and VulnName&quot;&gt;from O2Finding finding in o2Findings select new {finding.vulnType, finding.vulnName , finding}&lt;/script&gt;
        ///  &lt;script title=&quot;All Finding Details&quot;&gt;from O2Finding finding in o2Findings select f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string o2FindingsScriptLibrary {
            get {
                return ResourceManager.GetString("o2FindingsScriptLibrary", resourceCulture);
            }
        }
    }
}
