//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.Platform.External.SharpDevelop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImagesForControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImagesForControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Platform.External.SharpDevelop.Resources.ImagesForControls", typeof(ImagesForControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap btCompileCode_Image {
            get {
                object obj = ResourceManager.GetObject("btCompileCode_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btDebugMethod_Image {
            get {
                object obj = ResourceManager.GetObject("btDebugMethod_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btDragAssemblyCreated_Image {
            get {
                object obj = ResourceManager.GetObject("btDragAssemblyCreated_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btExecuteAssemblyUnderDebug_Image {
            get {
                object obj = ResourceManager.GetObject("btExecuteAssemblyUnderDebug_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btExecuteMethodWithoutDebugger_Image {
            get {
                object obj = ResourceManager.GetObject("btExecuteMethodWithoutDebugger_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btExecuteOnExternalEngine_Image {
            get {
                object obj = ResourceManager.GetObject("btExecuteOnExternalEngine_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btExecuteSelectedMethod_Image {
            get {
                object obj = ResourceManager.GetObject("btExecuteSelectedMethod_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btOpenFile_Image {
            get {
                object obj = ResourceManager.GetObject("btOpenFile_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btSaveFile_Image {
            get {
                object obj = ResourceManager.GetObject("btSaveFile_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btSeachAndViewAst_Image {
            get {
                object obj = ResourceManager.GetObject("btSeachAndViewAst_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btSelectedLineHistory_Image {
            get {
                object obj = ResourceManager.GetObject("btSelectedLineHistory_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btSettings_Image {
            get {
                object obj = ResourceManager.GetObject("btSettings_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btShowAssemblyExecutionPanel_Image {
            get {
                object obj = ResourceManager.GetObject("btShowAssemblyExecutionPanel_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btShowHideCompilationErrors_Image {
            get {
                object obj = ResourceManager.GetObject("btShowHideCompilationErrors_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btShowHidePythonLogExecutionOutputData_Image {
            get {
                object obj = ResourceManager.GetObject("btShowHidePythonLogExecutionOutputData_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btShowLogs_Image {
            get {
                object obj = ResourceManager.GetObject("btShowLogs_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap tbShowO2ObjectModel_Image {
            get {
                object obj = ResourceManager.GetObject("tbShowO2ObjectModel_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
